### ISSUE TITLE
Authentication Events

### ISSUE THREAD

**Issue by beredim** [mariovalney/laravel-keycloak-web-guard#18]
Laravel newbie here.
Is there any way for this to plug-in to https://laravel.com/docs/7.x/authentication#events ?
Or any suggestions on how to approach something like that when using laravel-keycloak-web-guard ?

**Comment by mariovalney** [comment]
Hi Beredim.

No, we do not implement any event on Auth process by now.

I'll add this as feature request.

**Comment by neemiasjr** [comment]
Hi Mario Valney,

I opened this PR to this enhancement.

https://github.com/mariovalney/laravel-keycloak-web-guard/pull/98

**Comment by mariovalney** [comment]
DONE. Thanks!
