### ISSUE TITLE
What is best way to save data of the first time user authenticates?

### ISSUE THREAD

**Issue by sachinuthale** [mariovalney/laravel-keycloak-web-guard#54]
Hello, 

I am using my own model with driver: keycloak-users, What is best way to save the name and email of the first time log in user to the application db ??

Currently i am able to save to the table, but i want to know is their any best way to do in service provider ??

**Comment by mariovalney** [comment]
Hi. 

I'm not sure what you are trying to achieve.
But you can use [DB facade](https://laravel.com/docs/8.x/queries#insert-statements) to save data to another table in laravel.

**Comment by sachinuthale** [comment]
Hello,

Thank you for response :).

In my application user needs to create a team, so user creating a team using email id.
So i am just need to check the user coming from keycloak is already in my db or not ??
if already in db can go further, else need to add that user to table.

**Comment by sachinuthale** [comment]
Currently i have written the middleware, which will check the email is present or not, if not insert and done.

**Comment by mariovalney** [comment]
I guess that's a good solution.
Do you need more help?

**Comment by sachinuthale** [comment]
No Sir, Thank you for response.

Mentioned solution works fine for me.
