### ISSUE TITLE
Using database sessions not working due to the email being used as key

### ISSUE THREAD

**Issue by philiplb** [mariovalney/laravel-keycloak-web-guard#56]
Hi,

we are using the database for storing the sessions with the recommended schema:

```PHP
Schema::create('sessions', function (Blueprint $table) {
    $table->string('id')->primary();
    $table->foreignId('user_id')->nullable()->index();
    $table->string('ip_address', 45)->nullable();
    $table->text('user_agent')->nullable();
    $table->text('payload');
    $table->integer('last_activity')->index();
});
```

But using the given model in the provider like this (auth.php):
```PHP
'providers' => [
    'users' => [
        'driver' => 'keycloak-users',
        'model' => Vizir\KeycloakWebGuard\Models\KeycloakUser::class,
    ],
],
```

It results in an exception when it tries to store the session:

> [previous exception] [object] (PDOException(code: 22P02): SQLSTATE[22P02]: Invalid text representation: 7 ERROR:  invalid input syntax for type bigint: \"foo@bar.com\" at /var/www/laravel/vendor/laravel/framework/src/Illuminate/Database/Connection.php:510)

What could I do here?

**Comment by mariovalney** [comment]
I'm not sure, but you can try.

_I guess Session Provider is agnostic enough to accept user_id as string._
