### ISSUE TITLE
Error callback, save session

### ISSUE THREAD

**Issue by tporto** [mariovalney/laravel-keycloak-web-guard#63]
![image](https://user-images.githubusercontent.com/4909952/152049868-40809ca2-b14c-4f30-a8c5-a993f7f99fe3.png)

**Comment by tporto** [comment]
When I return to the callback, I'm having this because it's trying to save the email used in the login in the user_id, is it really necessary to save it in the session? There's a way to disable it, I've tried and I couldn't.

**Comment by tporto** [comment]
Sorry for my ignorance, I've never worked with keycloak. I'm trying to implement it on a legacy system.

**Comment by mariovalney** [comment]
No problem, Thiago.
I just don't have time to answer always, but you can keep asking.
