### ISSUE TITLE
Logout error

### ISSUE THREAD

**Issue by deyvidcorbee** [mariovalney/laravel-keycloak-web-guard#70]
I'm having this error only on logout, do you know what it could be?
Everything works except logout via laravel. Even logout via the keycloak link works.
Laravel: 9
Keycloak: 18
![keycloak_logout_error](https://user-images.githubusercontent.com/83619869/164994312-656c9ca6-1267-47b2-ac0f-4e59ba40a99b.png)

**Comment by mariovalney** [comment]
Hi. This is a Keycloak error.
Please check your configuration.

[Check here for solution](https://syntaxfix.com/question/989/keycloak-invalid-parameter-redirect-uri#:~:text=If%20you're%20getting%20this,redirect_uri%20is%20also%20using%20http%20.)

[Docs about client configuration](https://www.keycloak.org/docs/latest/server_admin/index.html#proc-creating-oidc-client_server_administration_guide)
